# Start with a base image that has Java 17 installed.
FROM registry.access.redhat.com/ubi8/openjdk-17:1.15

# Copy the special Maven files that help us download dependencies.
COPY  .mvn/ .mvn

# Copy only essential Maven files required to download dependencies.
COPY mvnw pom.xml .

# Copy our actual project files (code, resources, etc.) into the container.
COPY  src ./src

RUN ./mvnw clean package -DskipTests -Dcheckstyle.skip=true

USER 185
EXPOSE 8080
COPY --chown=185  target/*.jar .

ENTRYPOINT ["java", "-jar", "./spring-petclinic-3.1.0-SNAPSHOT.jar"]
